### ISSUE TITLE
Return from triangulate() not suitable for to_svg

### ISSUE THREAD

**Issue by ConradHughes** [mesheldrake/Math-Geometry-Delaunay#6]
Thanks so much for writing this - I've found it really useful!

One minor note: to_svg() fails when called with the output of triangulate().  The docs suggest that to_svg expects just a hash, but it actually gets an mgd_topo, which causes to_svg to go to line 1316, failing on the $triio->pointlist call. Unblessing the topology solves the problem.

**Comment by mesheldrake** [comment]
Unblessing the topology hash will probably cause memory leaks. The topology hash was only blessed to add a DESTROY method that helps garbage collection work correctly.

Thanks for catching this. Fixed to_svg() to detect both HASH and mgd_topo.
